export const brands = [
	["dolce-gabbana", "Dolce & Gabbana"],
	["hermes", "Hermès"],
	["herve-leger", "Hervé Léger"],
	["iris-van-herpen", "Iris van Herpen"],
	["loewe", "Loewe"],
	["saint-laurent", "Saint Laurent"],
	["zac-posen", "Zac Posen"],
	["anna-sui", "Anna Sui"],
	["atelier-versace", "Atelier Versace"],
	["balenciaga", "Balenciaga"],
	["balmain", "Balmain"],
	["bottega-veneta", "Bottega Veneta"],
	["celine", "Celine"],
	["chanel", "Chanel"],
	["chloe", "Chloe"],
	["christian-dior", "Christian Dior"],
	["elie-saab", "Elie Saab"],
	["fendi", "Fendi"],
	["giambattista-valli", "Giambattista Valli"],
	["givenchy", "Givenchy"],
	["jacquemus", "Jacquemus"],
	["jean-paul-gaultier", "Jean Paul Gaultier"],
	["louis-vuitton", "Louis Vuitton"],
	["mugler", "Mugler"],
	["prada", "Prada"],
	["ralph-lauren", "Ralph Lauren"],
	["schiaparelli", "Schiaparelli"],
	["valentino", "Valentino"],
	["versace", "Versace"],
];

